### ISSUE TITLE
OptionC: adding registerUserFunction

### ISSUE THREAD

**Issue by YunchuWang** [ejizba/func-nodejs-prototype#1]
Personally favor optionC for two reasons:
1. ~~With a central object like app for managing functions, it is more intuitive for users to know/look up methods compared to option1 via intellijsense. (ex, typing app. autocompletes list of methods)~~ Moved to [#3](https://github.com/ejizba/func-nodejs-prototype/issues/3)
2. Making debugging easier for knowing which trigger/binding registration causes the error. As each register call adds one binding, any raised error is directly thrown from that method call instead of the whole registerFunction call in OptionA and OptionB. This is more intuitive to me to debug as method name in stack trace directly tells which particular binding failed to be registered and at which line number (if user wraps each register call per line).

Suggestions:
1. Making registerFunction take function name or function general information only and create a registerTrigger function separately.
2. Making a registerUserFunction method to take in user defined function separately to decouple trigger registration from user function registration.

**Comment by ejizba** [comment]
We did use a lot of this feedback, including a lot of stuff from option c. See here for more info: https://aka.ms/AzFuncNodeV4

Further feedback on this should be filed on the new, more official repo here: https://github.com/Azure/azure-functions-nodejs-library/issues
