### ISSUE TITLE
Remove name property from trigger binding options

### ISSUE THREAD

**Issue by hossam-nasr** [ejizba/func-nodejs-prototype#10]
This issue is specifically relevant to option C - Simple Objects.

In the old programming model, every binding, including trigger bindings, included a name property. This name could be used to access the binding using `context.bindings`. Example using timer trigger:

In `function.json`:

```TS
"bindings": [
    {
      "name": "myTimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 */5 * * * *"
    }
  ],
```

In `index.ts`:

```TS
const timerTrigger: AzureFunction = async function (context: Context, myTimer1: any): Promise<void> {
    const myTimer2 = context.bindings.myTimer;
    var timeStamp = new Date().toISOString();
    
    if (myTimer1.isPastDue)
    {
        context.log('Timer function is running late!');
    }
    context.log('Timer trigger function ran!', timeStamp);   
};
```

Here, `myTimer1` and `myTimer2` point to the same object! We see that the name of the second argument to the function does _not_ need to match the `name` property in the binding definition, since the trigger binding is always the second argument to the function (and every function has one and only one trigger). The only context in which this `name` property becomes relevant is when accessing the trigger binding through `context.bindings`, in which case `context.bindings.myTrigger` needs to match `myTrigger` in the binding definition. 

To avoid confusion, and to simplify defining functions, we should always make all triggers the second argument to the function, and _not_ support accessing trigger bindings through `context.bindings`, rendering the `name` property of _trigger_ binding definition obsolete.

So, for option C, instead of:

```TS
app.addTimerFunction('TimerTrigger1', { name: 'myTimer', schedule: '0 */5 * * * *', }, timerTrigger1);
```

We would have:

```TS
app.addTimerFunction('TimerTrigger1', { schedule: '0 */5 * * * *', }, timerTrigger1);
```

**Comment by ejizba** [comment]
For now we largely got rid of name for bindings. See here for more info: https://aka.ms/AzFuncNodeV4

Further feedback on this should be filed on the new, more official repo here: https://github.com/Azure/azure-functions-nodejs-library/issues
