### ISSUE TITLE
Option C: Provide an option to register more than one output binding at once?

### ISSUE THREAD

**Issue by hossam-nasr** [ejizba/func-nodejs-prototype#11]
Currently, Option C uses method chaining to register bindings, which is cool because it provides intelliscence, but could potentially make it cumbersome to register a lot of bindings to the same function.

Is it worth adding a way of registering more than one binding at once, sacrificing intelliscence?

Suggestions:

1. An additional `.addOutputs`/`addInputs` methods to the `Function` class:

```TS
addOutputs(outputOptions: OutputOptions[]): Function;
```

2. An additional (optional?) argument to the `add` methods:

```TS
addQueueInput(options: QueueInputOptions, bindings: bindingOptions[]): Function;
```

**Comment by ejizba** [comment]
For now we did not go with chaining, so this is not relevant. See here for more info: https://aka.ms/AzFuncNodeV4

Further feedback on this should be filed on the new, more official repo here: https://github.com/Azure/azure-functions-nodejs-library/issues
