### ISSUE TITLE
`eventGrid` does not exist on namespace `app`

### ISSUE THREAD

**Issue by nturinski** [ejizba/func-nodejs-prototype#12]
Seeing the following error when I try to run the project:
```
src/functions/eventGridTrigger1.ts:1:15 - error TS2305: Module '"@azure/functions"' has no exported member 'EventGridEvent'.
import { app, EventGridEvent, InvocationContext } from "@azure/functions";
src/functions/eventGridTrigger1.ts:7:5 - error TS2339: Property 'eventGrid' does not exist on type 'typeof app'.
app.eventGrid('eventGridTrigger1', {
```

Sure enough, I don't see it in the `index.d.ts` file. I have `"@azure/functions": "^4.0.0-alpha.2"` installed.

**Comment by ejizba** [comment]
Just pushed a commit to delete the event grid trigger for now: https://github.com/ejizba/func-nodejs-prototype/commit/1b3850c67c49840479518ae8dda4cd2f1a5f630e

That stuff is still in PR in the package: https://github.com/Azure/azure-functions-nodejs-library/pull/20
