### ISSUE TITLE
is the new function model deployable to azure?

### ISSUE THREAD

**Issue by jamiehaywood** [ejizba/func-nodejs-prototype#19]
with `3.5.2` released and the Azure Function Host now updated to `4.15.0` https://github.com/Azure/azure-functions-host/releases/tag/v4.15.0 - does this mean we can use the new function model (sans `host.json`)?

**Comment by ejizba** [comment]
Yes! Host v4.14.0 just finished rolling out meaning the new model is deployable to Azure now (FYI, the timing of the github releases doesn't mean much. They happen at the beginning of the release cycle not the end, and releases sometimes overlap). See here for instructions: https://aka.ms/AzFuncNodeV4

That being said, we have _not_ announced an official public preview yet so expect some rough edges. [Here](https://github.com/Azure/azure-functions-nodejs-worker/issues/638) and [here](https://github.com/Azure/azure-functions-host/pull/8900) are a few examples of things that still need to roll out, but they're edge case scenarios so hopefully wouldn't affect you.

Lastly, to clarify the new model is sans `functions.json`. We still require a `host.json`
