### ISSUE TITLE
Functions are not working on Azure 

### ISSUE THREAD

**Issue by camila-acosta** [ejizba/func-nodejs-prototype#28]
Hello, 

Hope you can help me, I'm using this repo as a guide , followed the instructions as documented https://github.com/ejizba/func-nodejs-prototype 

I created a couple of dummy functions and the updated the settings to reflect with my new structure
![image](https://user-images.githubusercontent.com/67367750/218991482-2a0eca3b-ecbd-4e64-bffc-d370233ee33a.png)

It is all working fine locally 

![image](https://user-images.githubusercontent.com/67367750/218992924-d0a43cd3-7efd-42a2-ad83-89e13f81be16.png)

but when I want to deploy this to Azure, either via Visual Studio or via Azure Devops - [AzureFunctionApp@1 Task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v1?view=azure-pipelines) the functions don't work from Azure.

![image](https://user-images.githubusercontent.com/67367750/218993998-2ee9f722-7aa8-4783-b478-1bd2fe4ce070.png)

![image](https://user-images.githubusercontent.com/67367750/218989914-9f64a0a4-b217-4755-badd-116181b54144.png)

All the files are being deployed correctly to the function app:

![image](https://user-images.githubusercontent.com/67367750/218991189-25fe6fff-dffb-4581-916f-79fb82885bf4.png)

The function app  is running 
![image](https://user-images.githubusercontent.com/67367750/218991899-480b3ad2-50a5-4d26-8fc2-067690609e5d.png)

I am validating the settings and  it is using function extension version 4 and node 18

![image](https://user-images.githubusercontent.com/67367750/218992221-0c41d9f9-b34a-4d6d-8a8e-e5715f467ad0.png)

I have changed the package reference to azure function as below in an attempt to fix it without any luck
`"@azure/functions": "^4.0.0-alpha.8",`

Is there any other setting I should configure in Azure? Any help is really appreciated.

Thanks
Camila

**Comment by ejizba** [comment]
Hi, if you haven't already, I would recommend reading this doc: https://aka.ms/AzFuncNodeV4

Support in Azure is still under a feature flag. You can try it out by adding the app setting `AzureWebJobsFeatureFlags` set to `EnableWorkerIndexing`

**Comment by camila-acosta** [comment]
Oh Amazing @ejizba thank you very very much! I did read that over and over but I'm probably blind. I didn't realise the setting was to be set in azure as well, I only set this up in local.settings.json but it is now working form me

**Comment by ejizba** [comment]
No problem, the feature flag is going away soon (already fixed [here](https://github.com/Azure/azure-functions-host/issues/8847), but hasn't rolled out yet). We also hope to have official docs available soon, which should be a lot more comprehensive

**Comment by camila-acosta** [comment]
Thanks @ejizba do you know if this feature is available in both, windows and linux Azure Functions?

**Comment by ejizba** [comment]
Yeah should work on both. There's a few fixes still rolling out, but they're mostly edge cases (if you're using multiple workers or if you're using durable). If you hit any problems, please let us know!
