### ISSUE TITLE
What should we name registering a function

### ISSUE THREAD

**Issue by ejizba** [ejizba/func-nodejs-prototype#4]
Some top contenders:

1. app.registerQueueFunction
2. app.addQueueFunction
3. app.onQueueTrigger

NOTE: Specifically chose "queue" instead of "http" as "http" is more complicated

**Comment by hossam-nasr** [comment]
Another suggestion, which may or may not be combined with the above is chaining/namespaces. For example:

* app.storage.queue()
* app.servicebus.topic()
* app.servicebus.queue()

How this can be combined with the above:
* app.storage.queue.addFunction()
* app.storage.queue.registerFunction()
* app.storage.queue.add()
* app.storage.queue.on()

**Comment by ejizba** [comment]
For now we went with the shorthand names `app.http`, `app.timer`, `app.storageQueue`, etc.. See here for more info: https://aka.ms/AzFuncNodeV4

Further feedback on this should be filed on the new, more official repo here: https://github.com/Azure/azure-functions-nodejs-library/issues
