### ISSUE TITLE
How should we name adding HTTP triggers?

### ISSUE THREAD

**Issue by hossam-nasr** [ejizba/func-nodejs-prototype#6]
We could leave HTTP treatment the same as other triggers, using some options from #4, for example:

* app.registerHttpFunction()
* app.onHttp()

Or we could provide more HTTP-specific ways of registering a function, filling in some boilerplate with defaults. Examples/top contenders:

* `app.get('/httpRoute', () => {} )` / `app.post('/httpRoute', () => {})`
* `app.route('/httpRoute', ['get', 'post'], () => {})`
* app.onRequest()
* app.http()
* `app.http.on(['get', 'post'], '/httpRoute', () => {})`

**Comment by ejizba** [comment]
For now we went with `app.http` if you want to specify a method and `app.get`, `app.post`, etc. as shorthand to not specify a method in the options. See here for more info: https://aka.ms/AzFuncNodeV4

Further feedback on this should be filed on the new, more official repo here: https://github.com/Azure/azure-functions-nodejs-library/issues
