### ISSUE TITLE
How should we name timer triggers?

### ISSUE THREAD

**Issue by hossam-nasr** [ejizba/func-nodejs-prototype#7]
Similar to #6, we could use standard Azure terminology from #4, or we could provide less Azure-like and more Node-like alternatives. Top contenders:

* app.timer()
* app.schedule()
* app.setInterval()
* app.every()

**Comment by ejizba** [comment]
For now we went with `app.timer`. See here for more info: https://aka.ms/AzFuncNodeV4

Further feedback on this should be filed on the new, more official repo here: https://github.com/Azure/azure-functions-nodejs-library/issues
