### ISSUE TITLE
How should we register functions?

### ISSUE THREAD

**Issue by hossam-nasr** [ejizba/func-nodejs-prototype#9]
One way of doing this would be the way that is currently implemented in all prototypes, which is to have an `app.` function, which takes the function name as the first argument, then extra configuration arguments, then the function callback. Using Option C and a queue trigger as an example:

```TS
app.addQueueFunction('QueueTrigger1', queueTrigger1Options, queueTrigger1);
```

However, an alternative would be to instead define functions using `module.exports`, where the export name would become the function name, removing one argument from the `app.` function. As an example, the above could be rewritten as:

```TS
exports.QueueTrigger1 = app.queueFunction(queueTrigger1Options, queueTrigger1);
```

A caveat of the second method is that the names of the exports could be modified/shortened if a webpack is used. A user can either specify that the webpack shouldn't modify export names, or be okay with the actual function names being different than the one specified in the `main.ts` file.

We could choose of these approaches and stick to it, or we could support them both.

**Comment by ejizba** [comment]
For now we are using the `app.` method. See here for more info: https://aka.ms/AzFuncNodeV4

Further feedback on this should be filed on the new, more official repo here: https://github.com/Azure/azure-functions-nodejs-library/issues
